version: "3.7"
services:
  backend:
    environment:
      - FRONTEND_URL=
      - BACKEND_URL=
    env_file:
    - secrets.env
    build: ./backend
    restart: "no"
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    restart: "no"
    depends_on:
      - backend
    ports:
      - "4200:4200"