version: "3"
services:
  backend:
    build: ./backend
    restart: "no"
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    restart: "no"
    depends_on:
      - backend
    ports:
      - "4200:4200"