version: "3.7"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: quotes
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/data
  backend:
    environment:
      - FRONTEND_URL=http://localhost:4200
      - BACKEND_URL=http://backend:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: yarn start:dev:docker
  frontend:
    command: yarn start:docker
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
volumes:                         
  db_data: